export const artworks = [
  {
    id: 'rw-01',
    title_es: 'Horizonte Interno',
    title_en: 'Inner Horizon',
    category: 'recent',
    year: '2025',
    technique_es: 'Acrílico sobre lienzo',
    technique_en: 'Acrylic on canvas',
    dimensions: '140 x 120 cm',
    image: 'https://picsum.photos/seed/enrique-01/900/700',
    available: true,
    description_es: 'Composición abstracta con capas cromáticas y gestos amplios.',
    description_en: 'Abstract composition with layered color fields and broad gestures.',
  },
  {
    id: 'rw-02',
    title_es: 'Luz de Costa',
    title_en: 'Coastal Light',
    category: 'landscape',
    year: '2024',
    technique_es: 'Acrílico y pigmento mineral',
    technique_en: 'Acrylic and mineral pigment',
    dimensions: '160 x 100 cm',
    image: 'https://picsum.photos/seed/enrique-02/900/700',
    available: false,
    description_es: 'Paisaje contemporáneo inspirado en la costa mediterránea.',
    description_en: 'Contemporary landscape inspired by the Mediterranean coast.',
  },
  {
    id: 'wc-01',
    title_es: 'Atmósfera Azul',
    title_en: 'Blue Atmosphere',
    category: 'watercolour',
    year: '2023',
    technique_es: 'Acuarela sobre papel de algodón',
    technique_en: 'Watercolour on cotton paper',
    dimensions: '56 x 76 cm',
    image: 'https://picsum.photos/seed/enrique-03/900/700',
    available: true,
    description_es: 'Serie de transparencias y veladuras de gran sutileza.',
    description_en: 'A series of transparent washes and subtle overlays.',
  },
  {
    id: 'pr-01',
    title_es: 'Memoria del Territorio',
    title_en: 'Memory of Territory',
    category: 'previous',
    year: '2019',
    technique_es: 'Mixta sobre tabla',
    technique_en: 'Mixed media on board',
    dimensions: '110 x 90 cm',
    image: 'https://picsum.photos/seed/enrique-04/900/700',
    available: true,
    description_es: 'Obra de etapa anterior centrada en textura y materia.',
    description_en: 'Earlier period work focused on texture and materiality.',
  },
  {
    id: 'ac-01',
    title_es: 'Estructura Solar',
    title_en: 'Solar Structure',
    category: 'acrylic',
    year: '2022',
    technique_es: 'Acrílico sobre lino',
    technique_en: 'Acrylic on linen',
    dimensions: '130 x 130 cm',
    image: 'https://picsum.photos/seed/enrique-05/900/700',
    available: true,
    description_es: 'Geometría orgánica y contrastes cálidos.',
    description_en: 'Organic geometry with warm contrasts.',
  },
  {
    id: 'rw-03',
    title_es: 'Campo de Silencio',
    title_en: 'Field of Silence',
    category: 'recent',
    year: '2026',
    technique_es: 'Acrílico y grafito',
    technique_en: 'Acrylic and graphite',
    dimensions: '150 x 120 cm',
    image: 'https://picsum.photos/seed/enrique-06/900/700',
    available: true,
    description_es: 'Investigación abstracta sobre ritmo y pausa visual.',
    description_en: 'Abstract research around rhythm and visual pause.',
  },
];
